// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qscdvpjilmdygjiesxxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzY2R2cGppbG1keWdqaWVzeHhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5Mzg4NDAsImV4cCI6MjA2NDUxNDg0MH0.hJLFSiqA_MUq0eynySzgedMK34ycbm5pAgIkvqq9hjo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);